version: '3.1'

services:
  nest-service:
    container_name: nest
    restart: always
    build: ./services/nest/
    ports:
      - ${NEST_SERVICE_PORT}:${NEST_SERVICE_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/nest-data
    depends_on:
      - nestdb

  django-service:
    container_name: django
    restart: always
    build: ./services/django
    ports:
      - ${DJANGO_SERVICE_PORT}:${DJANGO_SERVICE_PORT}
    command: python dashboards/manage.py runserver 0.0.0.0:${DJANGO_SERVICE_PORT}
    volumes:
      - .:/django-data
    depends_on:
      - djangodb

  nestdb:
    container_name: nest-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata-nest:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: -p 5432

  djangodb:
    container_name: django-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
      POSTGRES_DB: ${DJANGO_DB_NAME}
    volumes:
      - pgdata-django:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    command: -p 5433
  # rabbitmq:
  #   image: "rabbitmq:3"
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - "rabbitmq_data:/data"

  #  keycloak:
  #    depends_on:
  #      - postgres
  #    container_name: local_keycloak
  #    environment:
  #      DB_VENDOR: postgres
  #      DB_ADDR: postgres
  #      DB_DATABASE: ${DB_NAME}
  #      DB_USER: ${DB_USER}
  #      DB_PASSWORD: ${DB_PASSWORD}
  #    image: sleighzy/keycloak
  #    ports:
  #      - "8080:8080"
  #    restart: unless-stopped

volumes:
  nest-data:
  django-data:
  pgdata-nest:
  pgdata-django:
