name: Nest.js Jest CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean install dependencies
        run: npm ci
      - name: Build the project
        working-directory: services/nest/
        run: npm run build
      - name: Run tests
        working-directory: services/nest/
        run: npm run test
